/**
 * Generates a Google Calendar template URL for a given session.
 * 
 * @param session - The session object containing title, selectedDate, selectedSlot, and meetLink.
 * @returns A string representing the Google Calendar render URL.
 */
export function generateGoogleCalendarLink(session: {
    sessionTitle: string;
    selectedDate: string;
    selectedSlot: string;
    meetLink?: string;
    duration?: number;
}) {
    // Parse Date and Time
    // selectedDate: "2026-03-28"
    // selectedSlot: "10:00 AM" or "2:00 PM"
    
    try {
        const [hourStr, period] = session.selectedSlot.split(' ');
        let [hours, minutes] = hourStr.split(':').map(Number);
        
        if (period === 'PM' && hours !== 12) hours += 12;
        if (period === 'AM' && hours === 12) hours = 0;
        
        const start = new Date(session.selectedDate);
        start.setHours(hours, minutes || 0, 0, 0);
        
        // Default duration = 30 minutes
        const end = new Date(start.getTime() + (session.duration || 30) * 60000);
        
        const formatDate = (date: Date) =>
            date.toISOString().replace(/[-:]|.\d+/g, "");
            
        const startStr = formatDate(start);
        const endStr = formatDate(end);
        
        const title = encodeURIComponent(session.sessionTitle);
        const details = encodeURIComponent(
            `SkillTrader Synchronization Session\n\nProtocol Access: ${session.meetLink || 'No link provided'}\n\nGenerated by SkillTrader Intelligence.`
        );
        const location = encodeURIComponent(session.meetLink || 'Virtual Session');
        
        return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${title}&dates=${startStr}/${endStr}&details=${details}&location=${location}`;
    } catch (error) {
        console.error("Error generating calendar link:", error);
        return null;
    }
}
